---
ci:
  # We rely on renovate to update it but there is no way to fully disable it
  # https://github.com/pre-commit-ci/issues/issues/83
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: quarterly
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  skip:
    - renovate-config-validator # container limits
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.13
    hooks:
      - id: uv-sync
      - id: uv-lock
        alias: lock
      - id: uv-lock
        name: "deps: upgrade via uv sync --upgrade"
        alias: deps
        args: ["--upgrade"]
        stages: [manual]
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.88.1
    hooks:
      - id: renovate-config-validator
        alias: renovate
        args: [--strict]
  - repo: https://github.com/pycontribs/mirrors-prettier
    # keep it before yamllint
    rev: v3.6.2
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.2.0
    hooks:
      - id: cspell
        # entry: codespell --relative
        args: [--relative, --no-progress, --no-summary]
        name: Spell check with cspell
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.33.3
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
        language_version: python3
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
        alias: toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-format
        alias: ruff
      - id: ruff-check
        args: ["--fix"]
        alias: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        # empty args needed in order to match mypy cli behavior
        args: [--strict]
        additional_dependencies:
          - actions-toolkit
          - pytest
  - repo: https://github.com/pycqa/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
        args:
          - --output-format=colorized
        additional_dependencies:
          - actions-toolkit
          - pytest
