---
name: dynamic-matrix
branding:
  color: purple
  icon: arrow-right-circle
description: Generate Dynamic Job Matrix for Python
inputs:
  min_python:
    description: Minimal version of python to be tested against.
    required: false
    default: "3.8"
  max_python:
    description: Maximal version of python to be tested against.
    required: false
    default: "3.14"
  default_python:
    description: Default version of python used by env.
    required: false
    default: "3.9"
  other_names:
    description: Newline separated list of other tox environments to include.
    default: ""
    required: false
  platforms:
    description: >
      Comma separated list of platforms on which to test.
      Allowed entries linux, windows, macos.
    default: linux
  linux:
    description: >
      Expansion strategy for linux, full or minmax.
    default: full
  windows:
    description: >
      Expansion strategy for windows, full or minmax.
    default: minmax # costly/slow
  macos:
    description: >
      Expansion strategy for windows, full or minmax.
    default: minmax # costly/slow
  skip_explode:
    description: >
      If changed to "1", it will disable generating jobs for each python
      version and will only return values for jobs inside 'other_names'.
    default: "0"

outputs:
  matrix_include:
    description: List of tox environments to be run
runs:
  using: docker
  image: Dockerfile
